jobs:
# Replace params / app_name with your heroku app name
- name: deploy-app
  plan:
  - aggregate:
    - get: exam-app
    - get: exam-infra
  - task: mvn_build
    file: exam-infra/concourse/java/task.yml
    input_mapping: {source: exam-app}

  - task: push_to_heroku
    file: exam-infra/concourse/heroku/push_master_to_heroku.yml
    input_mapping: {source: exam-app}
    params:
      app_name: ((heroku_app_name))
      heroku_email: ((heroku_email))
      heroku_api_token: ((heroku_api_key))


- name: infra
  plan:
  - aggregate:
    - get: exam-infra
  - task: apply
    file: exam-infra/concourse/terraform/task.yml
    input_mapping: {source: exam-infra}
    params:
      github_token: ((github_token))
      heroku_api_key: ((heroku_api_key))
      statuscake_api_key: ((statuscake_api_key))
      command: apply
      directories: |
          terraform
  - put: exam-infra
    params:
      repository: with-state
      rebase: true

      - name: build
        plan:
        - aggregate:
          - get: exam-app
            trigger: true
          - get: exam-infra
        - task: mvn_build
          file: exam-infra/concourse/java/task.yml #mvn_build task.yml
          input_mapping: {source: exam-app}
        - put: docker-image-app
          params:
            build: exam-app


            - name: deploy-ci
              plan:
              - aggregate:
                - get: exam-infra
                - get: docker-image-app
                  trigger: true
                  passed: [build]
              - task: push_to_heroku
                file: exam-infra/concourse/heroku/deploy_task.yml
                input_mapping: {source: docker-image-app}
                params:
                  app_name: ((heroku_app_name))
                  heroku_email: ((heroku_email))
                  heroku_api_token: ((heroku_api_key))

resources:

# Replace with your own repository
- name: app
  type: git
  source:
      uri: https://github.com/devopseks2018/app
      branch: master
      private_key: ((deploy_key_app))

# Replace with your own repository
- name: infra
  type: git
  source:
      uri: https://github.com/devopseks2018/infra
      branch: master
      private_key: ((deploy_key_infra))

- name: docker-image-app
  type: docker-image
  source:
  repository: registry.heroku.com/((heroku_app_name))/web
  username: ((heroku_email))
  password: ((heroku_api_key))
